### ISSUE TITLE
Type declarations are not exposed

### ISSUE THREAD

**Issue by unlight** [semrel-extra/topo#13]
## Issue type
* bug report

## Expected behavior
Typings exposed

## Actual behavior
Typings are not exposed, which leads to `no-unsafe-assignment` eslint errors

## Steps to reproduce
Check `package.json`, it does not contain `types`, `typings`, but `index.d.ts` exists in dist/tarball.

## Specifications
- version: 1.4.2

**Comment by antongolub** [comment]
Thanks for the report. Seems easy to fix.
